//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bot 147 gives low to bot 67 and high to bot 71
        ///bot 142 gives low to bot 128 and high to bot 164
        ///bot 47 gives low to bot 4 and high to bot 209
        ///bot 107 gives low to bot 194 and high to bot 103
        ///bot 102 gives low to bot 82 and high to bot 3
        ///bot 101 gives low to bot 46 and high to bot 111
        ///value 23 goes to bot 76
        ///bot 16 gives low to bot 203 and high to bot 32
        ///bot 30 gives low to output 20 and high to bot 31
        ///bot 170 gives low to bot 123 and high to bot 108
        ///value 3 goes to bot 122
        ///bot 176 gives low to bo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BalanceBotsInput {
            get {
                return ResourceManager.GetString("BalanceBotsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alice would gain 2 happiness units by sitting next to Bob.
        ///Alice would gain 26 happiness units by sitting next to Carol.
        ///Alice would lose 82 happiness units by sitting next to David.
        ///Alice would lose 75 happiness units by sitting next to Eric.
        ///Alice would gain 42 happiness units by sitting next to Frank.
        ///Alice would gain 38 happiness units by sitting next to George.
        ///Alice would gain 39 happiness units by sitting next to Mallory.
        ///Bob would gain 40 happiness units by sitting next to Alice.
        ///Bob would l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTHOActualIn {
            get {
                return ResourceManager.GetString("DTHOActualIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cpy 1 a
        ///cpy 1 b
        ///cpy 26 d
        ///jnz c 2
        ///jnz 1 5
        ///cpy 7 c
        ///inc d
        ///dec c
        ///jnz c -2
        ///cpy a c
        ///inc a
        ///dec b
        ///jnz b -2
        ///cpy c b
        ///dec d
        ///jnz d -6
        ///cpy 16 c
        ///cpy 17 d
        ///inc a
        ///dec d
        ///jnz d -2
        ///dec c
        ///jnz c -5.
        /// </summary>
        internal static string LeonardoMonorailInput {
            get {
                return ResourceManager.GetString("LeonardoMonorailInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wxupppln
        ///ducindyd
        ///rhszlyfu
        ///kouqvpue
        ///nwntizie
        ///feyhuurg
        ///qlgzsmya
        ///svwijujv
        ///tcmsiuly
        ///vyrnynvz
        ///nmidjjxd
        ///ciduttzr
        ///nofnijfo
        ///ghskpifp
        ///yoyvsxct
        ///aqwzgouh
        ///ihhkdayn
        ///lmwyapsl
        ///nxkdwnoq
        ///hdkcvjrr
        ///ecxvdbeg
        ///sfybsvuu
        ///gygvlghh
        ///ivokuftm
        ///grolarfj
        ///tgzpjlca
        ///lojlcrks
        ///bmxogggc
        ///iablmcem
        ///cractnta
        ///mpdrqxea
        ///bdvrqbky
        ///zymlyyyk
        ///dhengvth
        ///vrvvfnoo
        ///ibemygpu
        ///yjetqqrc
        ///yhvpkxxc
        ///rqfzoakw
        ///uihcznsn
        ///blovcrpx
        ///dkrfqpco
        ///xytyahwu
        ///corlghco
        ///gisliobo
        ///qifxxizh
        ///uykqywcf
        ///pfnpbllg
        ///kqcmwcsf
        ///jgfujsse
        ///klmgeozq
        ///gp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SANActualIn {
            get {
                return ResourceManager.GetString("SANActualIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eedadn
        ///drvtee
        ///eandsr
        ///raavrd
        ///atevrs
        ///tsrnev
        ///sdttsa
        ///rasrtv
        ///nssdts
        ///ntnada
        ///svetve
        ///tesnvt
        ///vntsnd
        ///vrdear
        ///dvrsen
        ///enarar.
        /// </summary>
        internal static string SANTestIn {
            get {
                return ResourceManager.GetString("SANTestIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vxupkizork-sgmtkzoi-pkrrehkgt-zxgototm-644[kotgr]
        ///mbiyqoxsm-pvygob-nocsqx-900[obmqs]
        ///veqtekmrk-ikk-hitpscqirx-334[nrtws]
        ///gvcskirmg-fyrrc-irkmriivmrk-932[rikmc]
        ///xmtjbzidx-xviyt-yzqzgjkhzio-187[yzfeu]
        ///bwx-amkzmb-kivlg-kwibqvo-lmaqov-798[bkmva]
        ///vcibutulxiom-ohmnuvfy-yaa-mylpcwym-890[iyaun]
        ///ajvyjprwp-lqxlxujcn-jwjuhbrb-251[muivb]
        ///szfyrqriuflj-avccpsvre-kirzezex-971[rezcf]
        ///kwvacumz-ozilm-akidmvomz-pcvb-uizsmbqvo-590[uslyz]
        ///ucynmlgxcb-afmamjyrc-jmegqrgaq-626[rybxt]
        ///oaxadrgx-pkq-abqdmfuaze-872[xtbnw]
        ///t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SecurityThroughObscurityIn {
            get {
                return ResourceManager.GetString("SecurityThroughObscurityIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc #1 has 17 positions; at time=0, it is at position 5.
        ///Disc #2 has 19 positions; at time=0, it is at position 8.
        ///Disc #3 has 7 positions; at time=0, it is at position 1.
        ///Disc #4 has 13 positions; at time=0, it is at position 7.
        ///Disc #5 has 5 positions; at time=0, it is at position 1.
        ///Disc #6 has 3 positions; at time=0, it is at position 0..
        /// </summary>
        internal static string TimingIsEverthingIn {
            get {
                return ResourceManager.GetString("TimingIsEverthingIn", resourceCulture);
            }
        }
    }
}
