//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wxupppln
        ///ducindyd
        ///rhszlyfu
        ///kouqvpue
        ///nwntizie
        ///feyhuurg
        ///qlgzsmya
        ///svwijujv
        ///tcmsiuly
        ///vyrnynvz
        ///nmidjjxd
        ///ciduttzr
        ///nofnijfo
        ///ghskpifp
        ///yoyvsxct
        ///aqwzgouh
        ///ihhkdayn
        ///lmwyapsl
        ///nxkdwnoq
        ///hdkcvjrr
        ///ecxvdbeg
        ///sfybsvuu
        ///gygvlghh
        ///ivokuftm
        ///grolarfj
        ///tgzpjlca
        ///lojlcrks
        ///bmxogggc
        ///iablmcem
        ///cractnta
        ///mpdrqxea
        ///bdvrqbky
        ///zymlyyyk
        ///dhengvth
        ///vrvvfnoo
        ///ibemygpu
        ///yjetqqrc
        ///yhvpkxxc
        ///rqfzoakw
        ///uihcznsn
        ///blovcrpx
        ///dkrfqpco
        ///xytyahwu
        ///corlghco
        ///gisliobo
        ///qifxxizh
        ///uykqywcf
        ///pfnpbllg
        ///kqcmwcsf
        ///jgfujsse
        ///klmgeozq
        ///gp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SANActualIn {
            get {
                return ResourceManager.GetString("SANActualIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eedadn
        ///drvtee
        ///eandsr
        ///raavrd
        ///atevrs
        ///tsrnev
        ///sdttsa
        ///rasrtv
        ///nssdts
        ///ntnada
        ///svetve
        ///tesnvt
        ///vntsnd
        ///vrdear
        ///dvrsen
        ///enarar.
        /// </summary>
        internal static string SANTestIn {
            get {
                return ResourceManager.GetString("SANTestIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vxupkizork-sgmtkzoi-pkrrehkgt-zxgototm-644[kotgr]
        ///mbiyqoxsm-pvygob-nocsqx-900[obmqs]
        ///veqtekmrk-ikk-hitpscqirx-334[nrtws]
        ///gvcskirmg-fyrrc-irkmriivmrk-932[rikmc]
        ///xmtjbzidx-xviyt-yzqzgjkhzio-187[yzfeu]
        ///bwx-amkzmb-kivlg-kwibqvo-lmaqov-798[bkmva]
        ///vcibutulxiom-ohmnuvfy-yaa-mylpcwym-890[iyaun]
        ///ajvyjprwp-lqxlxujcn-jwjuhbrb-251[muivb]
        ///szfyrqriuflj-avccpsvre-kirzezex-971[rezcf]
        ///kwvacumz-ozilm-akidmvomz-pcvb-uizsmbqvo-590[uslyz]
        ///ucynmlgxcb-afmamjyrc-jmegqrgaq-626[rybxt]
        ///oaxadrgx-pkq-abqdmfuaze-872[xtbnw]
        ///t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SecurityThroughObscurityIn {
            get {
                return ResourceManager.GetString("SecurityThroughObscurityIn", resourceCulture);
            }
        }
    }
}
